"""
DOCX Formatter

Generates Word documents from Report objects using python-docx.
Handles headings, tables, charts, and professional styling.

Requires: pip install python-docx
"""

import logging
import re
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from src.agents.publishing.publisher import Report

logger = logging.getLogger(__name__)


def format_report_docx(report: 'Report', output_path: str) -> str:
    """
    Generate a Word document from a Report object.

    Args:
        report: Report with title, narrative, charts, tables
        output_path: Where to save the .docx file

    Returns:
        Path to the generated file
    """
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Style configuration
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)

    # Title
    title = doc.add_heading(report.title, level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.LEFT

    # Metadata subtitle
    meta_parts = []
    meta_parts.append(report.created_at.strftime('%B %d, %Y'))
    if report.metadata.get('marketing_year'):
        meta_parts.append(f"MY {report.metadata['marketing_year']}")
    subtitle = doc.add_paragraph(' | '.join(meta_parts))
    subtitle.style = doc.styles['Subtitle']

    # Process narrative markdown
    _add_markdown_content(doc, report.narrative)

    # Add charts
    if report.charts:
        doc.add_heading('Charts', level=2)
        for chart_path in report.charts:
            try:
                doc.add_picture(chart_path, width=Inches(6.0))
                name = Path(chart_path).stem.replace('_', ' ').title()
                caption = doc.add_paragraph(name)
                caption.alignment = WD_ALIGN_PARAGRAPH.CENTER
                caption.style = doc.styles['Caption'] if 'Caption' in doc.styles else doc.styles['Normal']
            except FileNotFoundError:
                doc.add_paragraph(f"[Chart not found: {chart_path}]")

    # Footer
    doc.add_paragraph('')
    footer = doc.add_paragraph('Generated by RLC-Agent')
    footer.runs[0].font.size = Pt(8)
    footer.runs[0].font.color.rgb = RGBColor(149, 165, 166)

    doc.save(output_path)
    logger.info(f"DOCX saved: {output_path}")
    return output_path


def _add_markdown_content(doc, markdown: str):
    """Parse markdown and add to document."""
    from docx.shared import Pt

    lines = markdown.split('\n')
    in_table = False
    table_rows = []

    for line in lines:
        stripped = line.strip()

        # Table handling
        if stripped.startswith('|') and stripped.endswith('|'):
            cells = [c.strip() for c in stripped.strip('|').split('|')]
            if all(set(c) <= set('-: ') for c in cells):
                continue  # Skip separator
            table_rows.append(cells)
            in_table = True
            continue

        if in_table and table_rows:
            _add_table(doc, table_rows)
            table_rows = []
            in_table = False

        # Headings
        if stripped.startswith('### '):
            doc.add_heading(stripped[4:], level=3)
        elif stripped.startswith('## '):
            doc.add_heading(stripped[3:], level=2)
        elif stripped.startswith('# '):
            doc.add_heading(stripped[2:], level=1)
        elif stripped == '---':
            doc.add_paragraph('_' * 50)
        elif stripped.startswith('- ') or stripped.startswith('* '):
            p = doc.add_paragraph(stripped[2:], style='List Bullet')
        elif stripped == '':
            continue
        else:
            p = doc.add_paragraph()
            _add_formatted_text(p, stripped)

    # Flush remaining table
    if table_rows:
        _add_table(doc, table_rows)


def _add_table(doc, rows: list):
    """Add a markdown table to the document."""
    if not rows:
        return

    from docx.shared import Pt, RGBColor
    from docx.oxml.ns import nsdecls
    from docx.oxml import parse_xml

    n_cols = len(rows[0])
    table = doc.add_table(rows=len(rows), cols=n_cols)
    table.style = 'Light Grid Accent 1'

    for i, row_data in enumerate(rows):
        for j, cell_text in enumerate(row_data):
            if j < n_cols:
                cell = table.rows[i].cells[j]
                cell.text = cell_text
                for paragraph in cell.paragraphs:
                    paragraph.style.font.size = Pt(9)

    doc.add_paragraph('')  # Spacing after table


def _add_formatted_text(paragraph, text: str):
    """Add text with bold/italic formatting to a paragraph."""
    # Split by bold markers
    parts = re.split(r'(\*\*.+?\*\*)', text)
    for part in parts:
        if part.startswith('**') and part.endswith('**'):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
        else:
            # Handle italic within non-bold
            sub_parts = re.split(r'(\*.+?\*)', part)
            for sub in sub_parts:
                if sub.startswith('*') and sub.endswith('*'):
                    run = paragraph.add_run(sub[1:-1])
                    run.italic = True
                else:
                    paragraph.add_run(sub)
