"""
HTML Formatter

Converts Report objects into styled HTML suitable for email delivery
or web display. Handles markdown conversion, chart embedding, and
professional styling consistent with commodity market reports.
"""

import logging
import re
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from src.agents.publishing.publisher import Report

logger = logging.getLogger(__name__)


# Professional report styling
REPORT_CSS = """
body {
    font-family: 'Segoe UI', Calibri, Arial, sans-serif;
    color: #2c3e50;
    max-width: 800px;
    margin: 0 auto;
    padding: 20px;
    line-height: 1.6;
}
h1 {
    color: #1a5276;
    border-bottom: 3px solid #1a5276;
    padding-bottom: 10px;
    font-size: 24px;
}
h2 {
    color: #2471a3;
    margin-top: 30px;
    font-size: 18px;
}
h3 { color: #2e86c1; font-size: 15px; }
table {
    border-collapse: collapse;
    width: 100%;
    margin: 15px 0;
    font-size: 13px;
}
th {
    background-color: #1a5276;
    color: white;
    padding: 8px 12px;
    text-align: left;
}
td {
    border: 1px solid #d5d8dc;
    padding: 6px 12px;
}
tr:nth-child(even) { background-color: #f2f3f4; }
.metadata {
    color: #7f8c8d;
    font-size: 12px;
    margin-bottom: 20px;
}
.chart-container {
    text-align: center;
    margin: 20px 0;
}
.chart-container img {
    max-width: 100%;
    border: 1px solid #d5d8dc;
    border-radius: 4px;
}
.footer {
    margin-top: 40px;
    padding-top: 15px;
    border-top: 1px solid #d5d8dc;
    color: #95a5a6;
    font-size: 11px;
}
strong { color: #1a5276; }
em { color: #566573; }
"""


def format_report_html(report: 'Report') -> str:
    """
    Convert a Report object to styled HTML.

    Args:
        report: Report with title, narrative (markdown), charts, metadata

    Returns:
        Complete HTML document string
    """
    narrative_html = _markdown_to_html(report.narrative)

    # Build chart section
    chart_html = ""
    if report.charts:
        chart_sections = []
        for i, chart_path in enumerate(report.charts):
            name = Path(chart_path).stem.replace('_', ' ').title()
            # For email: use cid references. For file: use relative paths.
            chart_sections.append(
                f'<div class="chart-container">'
                f'<p><strong>{name}</strong></p>'
                f'<img src="cid:chart{i}" alt="{name}">'
                f'</div>'
            )
        chart_html = "\n".join(chart_sections)

    # Build table section
    table_html = ""
    if report.tables:
        table_html = "\n".join(_markdown_to_html(t) for t in report.tables)

    # Metadata line
    meta_parts = []
    if report.metadata.get('marketing_year'):
        meta_parts.append(f"Marketing Year: {report.metadata['marketing_year']}")
    if report.metadata.get('triggered_by'):
        meta_parts.append(f"Source: {report.metadata['triggered_by']}")
    meta_html = " | ".join(meta_parts) if meta_parts else ""

    timestamp = report.created_at.strftime('%Y-%m-%d %H:%M UTC')

    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{report.title}</title>
<style>{REPORT_CSS}</style>
</head>
<body>
<h1>{report.title}</h1>
<div class="metadata">{timestamp}{' | ' + meta_html if meta_html else ''}</div>

{narrative_html}

{chart_html}

{table_html}

<div class="footer">
    Generated by RLC-Agent | {timestamp}
</div>
</body>
</html>"""

    return html


def _markdown_to_html(text: str) -> str:
    """
    Convert markdown text to HTML. Handles headings, bold, italic,
    tables, lists, and paragraphs.
    """
    lines = text.split('\n')
    html_lines = []
    in_table = False
    in_list = False
    table_header_done = False

    for line in lines:
        stripped = line.strip()

        # Table rows
        if stripped.startswith('|') and stripped.endswith('|'):
            cells = [c.strip() for c in stripped.strip('|').split('|')]

            # Skip separator rows
            if all(set(c) <= set('-: ') for c in cells):
                table_header_done = True
                continue

            if not in_table:
                html_lines.append('<table>')
                in_table = True
                table_header_done = False

            tag = 'th' if not table_header_done else 'td'
            row = ''.join(f'<{tag}>{_inline_format(c)}</{tag}>' for c in cells)
            html_lines.append(f'<tr>{row}</tr>')
            continue

        if in_table:
            html_lines.append('</table>')
            in_table = False
            table_header_done = False

        # Lists
        if stripped.startswith('- ') or stripped.startswith('* '):
            if not in_list:
                html_lines.append('<ul>')
                in_list = True
            html_lines.append(f'<li>{_inline_format(stripped[2:])}</li>')
            continue

        if in_list and not (stripped.startswith('- ') or stripped.startswith('* ')):
            html_lines.append('</ul>')
            in_list = False

        # Headings
        if stripped.startswith('### '):
            html_lines.append(f'<h3>{_inline_format(stripped[4:])}</h3>')
        elif stripped.startswith('## '):
            html_lines.append(f'<h2>{_inline_format(stripped[3:])}</h2>')
        elif stripped.startswith('# '):
            html_lines.append(f'<h1>{_inline_format(stripped[2:])}</h1>')
        elif stripped == '---':
            html_lines.append('<hr>')
        elif stripped == '':
            html_lines.append('')
        else:
            html_lines.append(f'<p>{_inline_format(stripped)}</p>')

    # Close any open tags
    if in_table:
        html_lines.append('</table>')
    if in_list:
        html_lines.append('</ul>')

    return '\n'.join(html_lines)


def _inline_format(text: str) -> str:
    """Apply inline markdown formatting (bold, italic)."""
    # Bold: **text**
    text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
    # Italic: *text*
    text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)
    # Code: `text`
    text = re.sub(r'`(.+?)`', r'<code>\1</code>', text)
    return text
