#:kivy 1.11.1

<JDSCheckBox@Switch>:
    color: 0, 0, 0, 1
    size_hint: 1, 1

<JDSLabel@ButtonBehavior+Label>:
    text_size: self.size
    valign: 'top'
    halign: 'center'
    font_size: '13sp'
    color: 0, 0, 0, 1

<JDSLabelCheckBox@BoxLayout>:
    text: ''
    group: ''
    active: cb.active
    
    orientation:'vertical'
    JDSCheckBox:
        id: cb
    JDSLabel:
        text: root.text+" On" if cb.active else root.text+' Off'

<JDSView>:
    orientation: "vertical"
    button_state: label_out

    MDToolbar:
        id: toolbar
        title: ""
        md_bg_color: app.theme_cls.primary_color

    MDBottomNavigation:
        id: panel

        MDBottomNavigationItem:
            name: "files1"
            text: "JDS"
            icon: "owl"

            BoxLayout:
                orientation: 'vertical'
                Label:
                    size_hint:1,0.25
                    id:label_out
                    text: "Welcome to the Jacobsen Data Scrapper,\n Select a data source to scrape below"
                    color: 0, 0, 0, 1
                ProgressBar:
                    size_hint:1,0.25
                    id:status_update
                    value:1
                    min:0
                    max:1
                BoxLayout:
                    size_hint:1,0.25
                    orientation:'horizontal'
                    JDSLabelCheckBox:
                        id: GTT
                        text:"GTT"
                        group: 'opts1'

                    JDSLabelCheckBox:
                        id:LCFS
                        text:"LCFS"
                        group: 'opts2'

                    JDSLabelCheckBox:
                        id:EMTS
                        text:"EMTS"
                        group: 'opts3'

                    JDSLabelCheckBox:
                        id:EIA
                        text:"EIA"
                        group: 'opts4'
                Button:
                    size_hint:1,0.25
                    id: run_button
                    text: 'Run'
                    on_release: root.update()



        MDBottomNavigationItem:
            name: "files2"
            text: "Menu"
            icon: "menu"

            BoxLayout:
                orientation:'vertical'
                
                MDLabel:
                    size_hint:1,0.1
                    font_style: "Body1"
                    theme_text_color: "Primary"
                    text: "Database Credentials"
                    halign: "center"

                GridLayout:
                    size_hint:1,0.35
                    rows: 3
                    cols: 2
                    padding: 5
                    spacing: 5
                    Label:
                        text_size: self.size
                        size_hint:0.2,0.33
                        color: 0, 0, 0, 1
                        text:"Database Server:"
                    TextInput:
                        size_hint:0.8,0.33
                        text_size: self.size
                        id: d_server
                        text: 'jakescrape.mysql.database.azure.com'
                    Label:
                        text_size: self.size
                        size_hint:0.2,0.33
                        color: 0, 0, 0, 1
                        text:"Database User Name:"
                    TextInput:
                        size_hint:0.8,0.33
                        text_size: self.size
                        id: d_username
                        text: 'jakeadmin@jakescrape'
                    Label:
                        text_size: self.size
                        size_hint:0.2,0.33
                        color: 0, 0, 0, 1
                        text:"Database Password:"
                    TextInput:
                        size_hint:0.8,0.33
                        text_size: self.size
                        id: d_password
                        password: True
                        text: 'Gvc$35lkaaPq!'

                MDLabel:
                    size_hint:1,.1
                    font_style: "Body1"
                    theme_text_color: "Primary"
                    text: "GTT Credentials"
                    halign: "center"
                

                GridLayout:
                    size_hint:1,.45
                    rows: 4
                    cols: 2
                    padding: 5
                    spacing: 5
                    Label:
                        text_size: self.size
                        size_hint:0.2,0.25
                        color: 0, 0, 0, 1
                        text:"GTT User Name:"
                    TextInput:
                        size_hint:0.8,0.25
                        id: g_username
                        text: 'rodney.ndum@thejacobsen.com'
                    Label:
                        text_size: self.size
                        size_hint:0.2,0.25
                        color: 0, 0, 0, 1
                        text:"GTT Password:"
                    TextInput:
                        size_hint:0.8,0.25
                        id: g_password
                        password: True
                        text: 'e0367a'
                    Label:
                        text_size: self.size
                        size_hint:0.2,0.25
                        color: 0, 0, 0, 1
                        text:"Start Date:"
                    TextInput:
                        size_hint:0.8,0.25
                        id: start_date
                        text:'2019-01'
                    Label:
                        text_size: self.size
                        size_hint:0.2,0.25
                        color: 0, 0, 0, 1
                        text:"End Date"
                    TextInput:
                        size_hint:0.8,0.25
                        id: end_date
                        text:'2020-01'
